package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writePolicyFile(t *testing.T, dir, name, body string) string {
	t.Helper()
	path := filepath.Join(dir, name+".yaml")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

const noNetBody = "apiVersion: brig.sh/v1alpha1\nname: no-net\ndesc: nothing outbound\n" +
	"egress:\n  default: deny\n  allow:\n    - host: api.anthropic.com\n"

// A fresh install has no policy directory or policies in it. ls says so
// rather than printing nothing, so the reader knows the emptiness is
// expected and how to fix it.
func TestListPoliciesEmpty(t *testing.T) {
	t.Setenv("BRIG_POLICY_DIR", t.TempDir())
	out, err := captureStdout(t, listPolicies)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "no policies yet") {
		t.Errorf("empty directory did not say so: %q", out)
	}
}

func TestListPoliciesSortedAndSkipsABadFile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	writePolicyFile(t, dir, "b", "apiVersion: brig.sh/v1alpha1\nname: zzz\negress:\n  default: allow\n")
	writePolicyFile(t, dir, "a", noNetBody)
	writePolicyFile(t, dir, "bad", "apiVersion: brig.sh/v1alpha1\nname: broken\nunexpected: true\negress:\n  default: deny\n")

	// listPolicies never fails the command over one bad file: the failure
	// shows up on stderr, not as a returned error, so one broken policy
	// does not hide the ones that work.
	var out string
	warning := captureStderr(t, func() {
		var err error
		out, err = captureStdout(t, listPolicies)
		if err != nil {
			t.Fatalf("listPolicies returned an error over one bad file: %v", err)
		}
	})
	if !strings.Contains(warning, "bad.yaml") {
		t.Errorf("the broken file was not named on stderr: %q", warning)
	}
	if !strings.Contains(out, "no-net") || !strings.Contains(out, "zzz") {
		t.Errorf("both good policies were not listed: %q", out)
	}
	if strings.Index(out, "no-net") > strings.Index(out, "zzz") {
		t.Errorf("policies are not sorted by name: %q", out)
	}
}

// A directory listPolicies cannot even read is a different failure from an
// empty one: LoadAll returns a nil map only for that case, and "no policies
// yet" would be the wrong thing to say -- the truth is brig could not look.
func TestListPoliciesReturnsAnErrorForAnUnreadableDirectory(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root can read a mode-000 directory, so this cannot be reproduced")
	}
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	if err := os.Chmod(dir, 0o000); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(dir, 0o700)

	out, err := captureStdout(t, listPolicies)
	if err == nil {
		t.Fatal("listPolicies returned nil for an unreadable directory")
	}
	if strings.Contains(out, "no policies yet") {
		t.Errorf("an unreadable directory was reported as having no policies: %q", out)
	}
}

// create writes a starter document and opens it in the editor -- a no-op
// editor here, since the point of this test is what got written to disk.
func TestCreatePolicyWritesAStarter(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	stubEditor(t, `true`)

	if err := createPolicy([]string{"no-net"}); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "no-net.yaml")
	blob, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("nothing was written: %v", err)
	}
	if !strings.Contains(string(blob), "name: no-net") {
		t.Errorf("the starter is not a policy named no-net:\n%s", blob)
	}
	if _, err := readPolicyFile(path); err != nil {
		t.Errorf("the starter does not parse and validate on its own: %v", err)
	}
}

// A starter document is generated bytes, but the file it would replace might
// carry real edits -- create refuses to overwrite one without --force.
func TestCreatePolicyRefusesAnExistingFileWithoutForce(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `echo should not run >&2; exit 1`)

	if err := createPolicy([]string{"no-net"}); err == nil {
		t.Fatal("create overwrote an existing file without --force")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != noNetBody {
		t.Errorf("the existing file was changed:\n%s", after)
	}
}

// --force overrides the refusal above, and works whether it is typed before
// or after the name -- flag.Parse stops at the first bare word, so a flag
// after the name has to be lifted and re-parsed rather than left in Args.
func TestCreatePolicyForceOverwritesFlagAfterName(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `sed -i.bak 's/^desc:$/desc: replaced/' "$1"`)

	if err := createPolicy([]string{"no-net", "--force"}); err != nil {
		t.Fatalf("create --force after the name failed: %v", err)
	}
	after, err := os.ReadFile(filepath.Join(dir, "no-net.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(after), "replaced") {
		t.Errorf("the starter did not replace the old file:\n%s", after)
	}
}

// When the editor fails, create is left half done unless it also removes
// the starter it just wrote -- otherwise the command reports failure but
// brig policies lists the policy anyway, and a retry refuses because the
// file is already there.
func TestCreatePolicyRemovesTheStarterWhenTheEditorFails(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	stubEditor(t, `exit 1`)

	if err := createPolicy([]string{"no-net"}); err == nil {
		t.Fatal("create succeeded despite the editor failing")
	}
	if _, err := os.Stat(filepath.Join(dir, "no-net.yaml")); !os.IsNotExist(err) {
		t.Errorf("the starter was left on disk after the editor failed (stat err = %v)", err)
	}
}

// --force's overwrite is a different case: the file the editor failed to
// touch already existed before create ran, so removing it would leave the
// user with no file at all where they had one a moment ago.
func TestCreatePolicyForceKeepsTheFileWhenTheEditorFails(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `exit 1`)

	if err := createPolicy([]string{"no-net", "--force"}); err == nil {
		t.Fatal("create succeeded despite the editor failing")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("--force's file was removed after the editor failed, leaving none at all: %v", err)
	}
	if string(after) != noNetBody {
		t.Errorf("--force overwrote the real file with the starter before the editor even ran, "+
			"so the failing editor left the starter behind instead of the original content:\n%s", after)
	}
}

// The starter used to be written straight over path before the editor ran,
// so a --force whose editor then failed left the real content replaced by
// the blank starter -- the command reported failure, but the original was
// already gone. Written beside path instead and only renamed into place
// once the save parses, so a failing editor can never destroy it.
func TestCreatePolicyForceDoesNotLoseContentWhenTheEditorFails(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	const original = "apiVersion: brig.sh/v1alpha1\nname: no-net\n" +
		"desc: MY REAL CONTENT, DO NOT LOSE THIS\negress:\n  default: deny\n"
	path := writePolicyFile(t, dir, "no-net", original)
	stubEditor(t, `exit 1`)

	if err := createPolicy([]string{"no-net", "--force"}); err == nil {
		t.Fatal("create succeeded despite the editor failing")
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != original {
		t.Errorf("the real content was lost:\nwant %q\ngot  %q", original, after)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".tmp") {
			t.Errorf("a temp file was left behind: %v", e.Name())
		}
	}
}

// The same content must survive an editor that runs but produces something
// that does not parse: --force still must not touch the real file until
// the new content is known to be good.
func TestCreatePolicyForceDoesNotLoseContentOnABrokenSave(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	const original = "apiVersion: brig.sh/v1alpha1\nname: no-net\n" +
		"desc: MY REAL CONTENT, DO NOT LOSE THIS\negress:\n  default: deny\n"
	path := writePolicyFile(t, dir, "no-net", original)
	stubEditor(t, `printf 'name: [unclosed\n' > "$1"`)

	err := createPolicy([]string{"no-net", "--force"})
	if err == nil {
		t.Fatal("create succeeded despite an unparseable save")
	}
	after, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(after) != original {
		t.Errorf("the real content was lost:\nwant %q\ngot  %q", original, after)
	}
	scratchPath := strings.TrimSpace(strings.SplitAfter(err.Error(), "your edit is still at ")[1])
	if _, statErr := os.Stat(scratchPath); statErr != nil {
		t.Errorf("the error names a scratch file that does not exist: %v", statErr)
	}
}

// The name lives inside the file, not the filename, so a duplicate is
// possible even when the target path itself is free. create checks the
// name against every policy that already loads, not just the path it is
// about to write, and --force does not help here: forcing would only add
// a second file declaring the same name.
func TestCreatePolicyRefusesANameTakenByAnotherFile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	other := writePolicyFile(t, dir, "custom", noNetBody) // declares name: no-net
	stubEditor(t, `echo should not run >&2; exit 1`)

	for _, args := range [][]string{{"no-net"}, {"no-net", "--force"}} {
		if err := createPolicy(args); err == nil {
			t.Fatalf("createPolicy(%v) = nil, want an error: no-net is custom.yaml's name", args)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "no-net.yaml")); err == nil {
		t.Error("create wrote no-net.yaml despite the name being taken by custom.yaml")
	}
	after, err := os.ReadFile(other)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != noNetBody {
		t.Errorf("custom.yaml was changed:\n%s", after)
	}
}

// A directory create cannot even read is a different failure from a clean
// namespace to write into: LoadAll returns a nil map only for that case,
// and create must surface it rather than press on toward MkdirAll/WriteFile.
func TestCreatePolicyReturnsAnErrorForAnUnreadableDirectory(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root can read a mode-000 directory, so this cannot be reproduced")
	}
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	if err := os.Chmod(dir, 0o000); err != nil {
		t.Fatal(err)
	}
	defer os.Chmod(dir, 0o700)
	stubEditor(t, `echo should not run >&2; exit 1`)

	if err := createPolicy([]string{"no-net"}); err == nil {
		t.Fatal("createPolicy returned nil for an unreadable directory")
	}
}

// show prints YAML by default, and works whether --json is typed before or
// after the name -- the same flag-after-a-bare-word case create's force
// flag has.
func TestShowPolicyJSONFlagAfterName(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	writePolicyFile(t, dir, "no-net", noNetBody)

	out, err := captureStdout(t, func() error { return showPolicy([]string{"no-net"}) })
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "name: no-net") {
		t.Errorf("plain show is not YAML naming the policy: %q", out)
	}

	out, err = captureStdout(t, func() error { return showPolicy([]string{"no-net", "--json"}) })
	if err != nil {
		t.Fatalf("show --json after the name failed: %v", err)
	}
	var decoded map[string]any
	if err := json.Unmarshal([]byte(out), &decoded); err != nil {
		t.Fatalf("show --json did not print valid JSON: %v\n%s", err, out)
	}
	if decoded["name"] != "no-net" {
		t.Errorf("show --json printed the wrong policy: %v", decoded)
	}
}

// create checks the name before it ever builds a path from it, so a name
// like "../../notes" is refused rather than joined into a path that escapes
// the policy directory.
func TestCreatePolicyRefusesAnUnsafeNameBeforeTouchingDisk(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	stubEditor(t, `echo should not run >&2; exit 1`)

	if err := createPolicy([]string{"../../escape"}); err == nil {
		t.Fatal("an unsafe name was accepted")
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 0 {
		t.Errorf("create wrote something despite the unsafe name: %v", entries)
	}
}

// The starter template writes the name into the document unquoted, so a
// name YAML would read back as something else must be refused here, before
// create ever writes the file -- not just when a document is later parsed.
func TestCreatePolicyRefusesAnAmbiguousNameBeforeTouchingDisk(t *testing.T) {
	for _, name := range []string{"no", "0x10"} {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			t.Setenv("BRIG_POLICY_DIR", dir)
			stubEditor(t, `echo should not run >&2; exit 1`)

			if err := createPolicy([]string{name}); err == nil {
				t.Fatal("an ambiguous name was accepted")
			}
			entries, err := os.ReadDir(dir)
			if err != nil {
				t.Fatal(err)
			}
			if len(entries) != 0 {
				t.Errorf("create wrote something despite the ambiguous name: %v", entries)
			}
		})
	}
}

func TestShowUnknownPolicy(t *testing.T) {
	t.Setenv("BRIG_POLICY_DIR", t.TempDir())
	err := showPolicy([]string{"ghost"})
	if err == nil || !strings.Contains(err.Error(), "unknown policy") {
		t.Errorf("wrong error for an unknown name: %v", err)
	}
}

// lookupPolicy backs show, edit and rm alike, so an unreadable directory
// must surface as that failure through all three, not as "unknown policy"
// -- which would point the user at `brig policies`, and that would also
// fail to read the same directory.
func TestShowEditRemoveReportAnUnreadableDirectory(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("root can read a mode-000 directory, so this cannot be reproduced")
	}
	for _, run := range []struct {
		name string
		call func() error
	}{
		{"show", func() error { return showPolicy([]string{"no-net"}) }},
		{"edit", func() error { return editPolicy([]string{"no-net"}) }},
		{"rm", func() error { return removePolicy([]string{"no-net"}) }},
	} {
		t.Run(run.name, func(t *testing.T) {
			dir := t.TempDir()
			t.Setenv("BRIG_POLICY_DIR", dir)
			if err := os.Chmod(dir, 0o000); err != nil {
				t.Fatal(err)
			}
			defer os.Chmod(dir, 0o700)

			err := run.call()
			if err == nil {
				t.Fatal("returned nil for an unreadable directory")
			}
			if strings.Contains(err.Error(), "unknown policy") {
				t.Errorf("an unreadable directory was reported as an unknown policy: %v", err)
			}
		})
	}
}

func TestEditPolicyOpensAndSavesChanges(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `awk '!/^desc: nothing outbound$/' "$1" > "$1.new" && mv "$1.new" "$1" && `+
		`printf 'desc: edited\n' >> "$1"`)

	if err := editPolicy([]string{"no-net"}); err != nil {
		t.Fatalf("editing failed: %v", err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(after), "desc: edited") {
		t.Errorf("the editor's changes are not on disk:\n%s", after)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(entries) != 1 {
		t.Errorf("the scratch copy was not cleaned up: %v", entries)
	}
}

// The final write goes through a temp file in the same directory, then a
// rename, rather than truncating entry.Path in place -- so a crash between
// those two steps cannot leave it half written. The rename must not change
// the file's mode, and must leave no .tmp file behind either.
func TestEditPolicyWriteBackPreservesModeAndLeavesNoTempFile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `awk '!/^desc: nothing outbound$/' "$1" > "$1.new" && mv "$1.new" "$1" && `+
		`printf 'desc: edited\n' >> "$1"`)

	if err := editPolicy([]string{"no-net"}); err != nil {
		t.Fatalf("editing failed: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o644 {
		t.Errorf("file mode changed to %v after edit, want 0644", info.Mode().Perm())
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".tmp") {
			t.Errorf("a temp file was left behind: %v", e.Name())
		}
	}
}

// The rename replaces the file outright, so a mode other than the 0644
// every policy starts with has to be carried over by hand -- the previous
// test alone would not catch a regression here, since 0644 in and 0644 out
// looks identical whether the mode was preserved or just hardcoded again.
func TestEditPolicyPreservesANonDefaultMode(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	if err := os.Chmod(path, 0o600); err != nil {
		t.Fatal(err)
	}
	stubEditor(t, `awk '!/^desc: nothing outbound$/' "$1" > "$1.new" && mv "$1.new" "$1" && `+
		`printf 'desc: edited\n' >> "$1"`)

	if err := editPolicy([]string{"no-net"}); err != nil {
		t.Fatalf("editing failed: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Errorf("file mode changed to %v after edit, want 0600 preserved", info.Mode().Perm())
	}
}

// edit validates before saving: a broken save does not reach the real file
// at all, and the edit itself is not lost -- it stays in the scratch copy
// the error names.
func TestEditPolicyLeavesTheRealFileUntouchedOnABrokenSave(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `printf 'name: [unclosed\n' > "$1"`)

	err := editPolicy([]string{"no-net"})
	if err == nil {
		t.Fatal("a broken save was accepted")
	}
	after, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatalf("the file was removed: %v", readErr)
	}
	if string(after) != noNetBody {
		t.Errorf("the real file was changed by a save that did not validate:\n%s", after)
	}
	scratchPath := strings.TrimSpace(strings.SplitAfter(err.Error(), "your edit is still at ")[1])
	scratch, readErr := os.ReadFile(scratchPath)
	if readErr != nil {
		t.Fatalf("the scratch copy the error named does not exist: %v", readErr)
	}
	if !strings.Contains(string(scratch), "unclosed") {
		t.Errorf("the scratch copy does not hold the edit:\n%s", scratch)
	}
}

// A save that renames the policy onto a name a different file already
// declares must be refused: otherwise two files end up claiming one name,
// and nothing says so until the next listing.
func TestEditPolicyRefusesARenameIntoAnotherFilesName(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	otherBody := "apiVersion: brig.sh/v1alpha1\nname: staging\negress:\n  default: allow\n"
	other := writePolicyFile(t, dir, "staging", otherBody)
	stubEditor(t, `sed -i.bak 's/^name: no-net$/name: staging/' "$1"`)

	err := editPolicy([]string{"no-net"})
	if err == nil {
		t.Fatal("a rename onto another file's name was accepted")
	}
	if !strings.Contains(err.Error(), "staging") {
		t.Errorf("the error does not name the colliding policy: %v", err)
	}
	after, readErr := os.ReadFile(path)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(after) != noNetBody {
		t.Errorf("no-net.yaml was changed by a save that was refused:\n%s", after)
	}
	afterOther, readErr := os.ReadFile(other)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if string(afterOther) != otherBody {
		t.Errorf("staging.yaml was changed by an edit to a different file:\n%s", afterOther)
	}
}

// A rename to a name nothing else uses must still succeed: the check
// above must not mistake this file for a collision with itself.
func TestEditPolicyAllowsARenameToAFreeName(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)
	stubEditor(t, `sed -i.bak 's/^name: no-net$/name: totally-new/' "$1"`)

	if err := editPolicy([]string{"no-net"}); err != nil {
		t.Fatalf("a rename to an unused name was refused: %v", err)
	}
	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(after), "name: totally-new") {
		t.Errorf("the rename did not save:\n%s", after)
	}
}

func TestEditUnknownPolicy(t *testing.T) {
	t.Setenv("BRIG_POLICY_DIR", t.TempDir())
	err := editPolicy([]string{"ghost"})
	if err == nil || !strings.Contains(err.Error(), "unknown policy") {
		t.Errorf("wrong error for an unknown name: %v", err)
	}
}

func TestRemovePolicyDeletesTheFile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("BRIG_POLICY_DIR", dir)
	path := writePolicyFile(t, dir, "no-net", noNetBody)

	if err := removePolicy([]string{"no-net"}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("the file is still there")
	}
}

func TestRemoveUnknownPolicy(t *testing.T) {
	t.Setenv("BRIG_POLICY_DIR", t.TempDir())
	err := removePolicy([]string{"ghost"})
	if err == nil || !strings.Contains(err.Error(), "unknown policy") {
		t.Errorf("wrong error for an unknown name: %v", err)
	}
}

func TestPolicyCmdDispatch(t *testing.T) {
	if err := policyCmd(nil); err == nil {
		t.Error("no subcommand was accepted")
	}
	if err := policyCmd([]string{"bogus"}); err == nil {
		t.Error("an unknown subcommand was accepted")
	}
}
